=begin
#QAN AutoApi

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.0.2

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'date'
require 'time'

module OpenapiClient
  class OutputFeeHistory
    # A URL to the JSON Schema for this object.
    attr_accessor :schema

    # An array of block base fees per gas. This includes the next block after the newest of the returned range, because this value can be derived from the newest block. Zeroes are returned for pre-EIP-1559 blocks
    attr_accessor :base_fee_per_gas

    # An array of block gas used ratios. These are calculated as the ratio of gasUsed and gasLimit
    attr_accessor :gas_used_ratio

    # The lowest number block of the returned range encoded in decimal format
    attr_accessor :oldest_block

    # An array of effective priority fees per gas data points from a single block. All zeroes are returned if the block is empty
    attr_accessor :reward

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'schema' => :'$schema',
        :'base_fee_per_gas' => :'BaseFeePerGas',
        :'gas_used_ratio' => :'GasUsedRatio',
        :'oldest_block' => :'OldestBlock',
        :'reward' => :'Reward'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'schema' => :'String',
        :'base_fee_per_gas' => :'Array<String>',
        :'gas_used_ratio' => :'Array<Float>',
        :'oldest_block' => :'String',
        :'reward' => :'Array<Array<String>>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::OutputFeeHistory` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::OutputFeeHistory`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'schema')
        self.schema = attributes[:'schema']
      end

      if attributes.key?(:'base_fee_per_gas')
        if (value = attributes[:'base_fee_per_gas']).is_a?(Array)
          self.base_fee_per_gas = value
        end
      else
        self.base_fee_per_gas = nil
      end

      if attributes.key?(:'gas_used_ratio')
        if (value = attributes[:'gas_used_ratio']).is_a?(Array)
          self.gas_used_ratio = value
        end
      else
        self.gas_used_ratio = nil
      end

      if attributes.key?(:'oldest_block')
        self.oldest_block = attributes[:'oldest_block']
      else
        self.oldest_block = nil
      end

      if attributes.key?(:'reward')
        if (value = attributes[:'reward']).is_a?(Array)
          self.reward = value
        end
      else
        self.reward = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @base_fee_per_gas.nil?
        invalid_properties.push('invalid value for "base_fee_per_gas", base_fee_per_gas cannot be nil.')
      end

      if @gas_used_ratio.nil?
        invalid_properties.push('invalid value for "gas_used_ratio", gas_used_ratio cannot be nil.')
      end

      if @oldest_block.nil?
        invalid_properties.push('invalid value for "oldest_block", oldest_block cannot be nil.')
      end

      if @reward.nil?
        invalid_properties.push('invalid value for "reward", reward cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @base_fee_per_gas.nil?
      return false if @gas_used_ratio.nil?
      return false if @oldest_block.nil?
      return false if @reward.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          schema == o.schema &&
          base_fee_per_gas == o.base_fee_per_gas &&
          gas_used_ratio == o.gas_used_ratio &&
          oldest_block == o.oldest_block &&
          reward == o.reward
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [schema, base_fee_per_gas, gas_used_ratio, oldest_block, reward].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = OpenapiClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
