=begin
#QAN AutoApi

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.0.2

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::OutputSendRawTransaction
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::OutputSendRawTransaction do
  let(:instance) { OpenapiClient::OutputSendRawTransaction.new }

  describe 'test an instance of OutputSendRawTransaction' do
    it 'should create an instance of OutputSendRawTransaction' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::OutputSendRawTransaction)
    end
  end

  describe 'test attribute "schema"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "transaction_hash"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
