=begin
#QAN AutoApi

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.0.2

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::OutputGetTransactionReceipt
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::OutputGetTransactionReceipt do
  let(:instance) { OpenapiClient::OutputGetTransactionReceipt.new }

  describe 'test an instance of OutputGetTransactionReceipt' do
    it 'should create an instance of OutputGetTransactionReceipt' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::OutputGetTransactionReceipt)
    end
  end

  describe 'test attribute "schema"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "transaction_receipt"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
